FROM python:3.12

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple

WORKDIR /DicePP

COPY ./pyproject.toml /DicePP/pyproject.toml

RUN pip install --no-cache-dir --upgrade .

COPY ./ /DicePP

CMD ["python", "/DicePP/bot.py"]
