"""Shared DicePP instance layout and persistent-data catalog.

This package intentionally depends only on the Python standard library so the
Bot, Dashboard, and Manager can inspect instance data before starting NoneBot.
"""

from .assets import (
    ARCHIVE_PROFILE_FULL,
    ARCHIVE_PROFILE_REGULAR,
    BOT_CORE_ASSET,
    BOT_CORE_SCHEMA,
    BOT_LOG_ASSET,
    BOT_LOG_SCHEMA,
    BOT_CONFIGS_ASSET,
    CONTENT_ASSET,
    DATA_CATALOG,
    INSTANCE_DB_ASSET,
    INSTANCE_SCHEMA,
    LOCAL_IMAGES_ASSET,
    PERSONA_DB_ASSET,
    PERSONA_SCHEMA,
    USER_CONFIG_ASSET,
    DataAsset,
    DataAssetCatalog,
    DataAssetKind,
    DataAssetMatch,
    DataAssetRestoreTarget,
    SchemaReference,
)
from .layout import InstanceLayout
from .query_database import (
    QUERY_DATA_FIELDS,
    QUERY_DATA_OPTIONAL_FIELDS,
    QUERY_DATA_REQUIRED_FIELDS,
    QUERY_DATABASE_STATE_FILE,
    QUERY_REDIRECT_FIELDS,
    QueryDatabaseState,
    QueryDatabaseStateError,
    is_query_database_name,
    load_query_database_state,
    query_database_state_path,
    save_query_database_state,
    set_query_database_enabled,
)
from .query_normalize import (
    DEFAULT_QUERY_NORMALIZATION_LIMITS,
    MAX_LEGACY_DIRECTIVE_CHARS,
    MAX_LEGACY_DIRECTIVES,
    MAX_LEGACY_QUERY_MATCHES,
    MAX_NORMALIZED_CONTENT_CHARS,
    QueryNormalizationCounts,
    QueryNormalizationIssue,
    QueryNormalizationLimits,
    QueryNormalizationRedirect,
    QueryNormalizationReport,
    QueryNormalizationRow,
    legacy_v1_command_split,
    normalize_query_database,
)

__all__ = [
    "ARCHIVE_PROFILE_FULL",
    "ARCHIVE_PROFILE_REGULAR",
    "BOT_CONFIGS_ASSET",
    "BOT_CORE_ASSET",
    "BOT_CORE_SCHEMA",
    "BOT_LOG_ASSET",
    "BOT_LOG_SCHEMA",
    "CONTENT_ASSET",
    "DATA_CATALOG",
    "DEFAULT_QUERY_NORMALIZATION_LIMITS",
    "INSTANCE_DB_ASSET",
    "INSTANCE_SCHEMA",
    "LOCAL_IMAGES_ASSET",
    "MAX_LEGACY_DIRECTIVE_CHARS",
    "MAX_LEGACY_DIRECTIVES",
    "MAX_LEGACY_QUERY_MATCHES",
    "MAX_NORMALIZED_CONTENT_CHARS",
    "PERSONA_DB_ASSET",
    "PERSONA_SCHEMA",
    "QUERY_DATA_FIELDS",
    "QUERY_DATA_OPTIONAL_FIELDS",
    "QUERY_DATA_REQUIRED_FIELDS",
    "QUERY_DATABASE_STATE_FILE",
    "QUERY_REDIRECT_FIELDS",
    "USER_CONFIG_ASSET",
    "DataAsset",
    "DataAssetCatalog",
    "DataAssetKind",
    "DataAssetMatch",
    "DataAssetRestoreTarget",
    "InstanceLayout",
    "QueryDatabaseState",
    "QueryDatabaseStateError",
    "QueryNormalizationCounts",
    "QueryNormalizationIssue",
    "QueryNormalizationLimits",
    "QueryNormalizationRedirect",
    "QueryNormalizationReport",
    "QueryNormalizationRow",
    "SchemaReference",
    "is_query_database_name",
    "legacy_v1_command_split",
    "load_query_database_state",
    "normalize_query_database",
    "query_database_state_path",
    "save_query_database_state",
    "set_query_database_enabled",
]
