LOC_FAVOR_SHOW = "favor_show"
LOC_FAVOR_BLOCK = "favor_block"
LOC_FAVOR_PHASE_HAPPY = "favor_phase_happy"
LOC_FAVOR_PHASE_COMMON = "favor_phase_common"
LOC_FAVOR_PHASE_UNGOOD = "favor_phase_ungood"
LOC_FAVOR_PHASE_ANGRY = "favor_phase_angry"
LOC_FAVOR_PHASE_BLOCK = "favor_phase_block"

CFG_FAVOR_DEFAULT = "favor_default"
CFG_FAVOR_MAX = "favor_max"
CFG_FAVOR_MIN = "favor_min"
CFG_FAVOR_DALIY_CHANGE_MAX = "favor_daliy_change_max"
CFG_FAVOR_HAPPY_VAR = "favor_happy_var"
CFG_FAVOR_COMMON_VAR = "favor_common_var"
CFG_FAVOR_UNGOOD_VAR = "favor_ungood_var"
CFG_FAVOR_ANGRY_VAR = "favor_angry_var"
CFG_FAVOR_BLOCK_VAR = "favor_block_var"

CFG_FAVOR_MOD_BLOCK = "favor_mod_block"
CFG_FAVOR_MOD_USE = "favor_mod_use"
CFG_FAVOR_MOD_NATURE = "favor_mod_nature"
CFG_FAVOR_MOD_REPEAT = "favor_mod_repeat"
CFG_FAVOR_MOD_WRONG_USE = "favor_mod_wrong_use"

DC_FAVOR = "favor"
