"""
Local control token: generated by Bot, read-only by Dashboard.

The token lives at ``data/runtime/local-control.token`` inside the DicePP
project root.  Bot creates it on first boot; Dashboard reads it on startup.
Both sides agree on the path, no out-of-band configuration needed.
"""
import os
import secrets
from pathlib import Path


_TOKEN_FILENAME = "local-control.token"


def token_path(project_root: Path) -> Path:
    """Absolute path to the local control token file."""
    return project_root / "data" / "runtime" / _TOKEN_FILENAME


def ensure_token(project_root: Path) -> str:
    """Read existing token, or generate + persist a new one. Returns the token."""
    path = token_path(project_root)
    if path.exists():
        return path.read_text(encoding="utf-8").strip()

    token = secrets.token_hex(32)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(token, encoding="utf-8")
    return token


def read_token(project_root: Path) -> str | None:
    """Read the token, or return None if it has not been generated yet."""
    path = token_path(project_root)
    if not path.exists():
        return None
    return path.read_text(encoding="utf-8").strip()
